name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências e build da API
        run: |
          dotnet restore EmporioTerere.Api/EmporioTerere.Api.csproj
          dotnet build EmporioTerere.Api/EmporioTerere.Api.csproj --configuration Release --no-restore --verbosity minimal

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Rodar testes unitários
        run: dotnet test EmporioTerere.Tests/EmporioTerere.Tests.csproj --no-build --configuration Release --verbosity normal

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publicar aplicação
        run: dotnet publish EmporioTerere.Api/EmporioTerere.Api.csproj -c Release -o ./publish

  docker:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build da Docker image
        run: docker build -t emporioterere:latest .
